### PR TITLE
Check for unclosed lock in read-dbs

### LINKED ISSUE #42: LOCK: The process cannot access the file because it is being used by another process
`levelmeup run example11.js`

`levelmeup verify example11.js`

gives :

```
events.js:85
      throw er; // Unhandled 'error' event
OpenError: IO error: LockFile ~levelmeup_1_4520/LOCK: The process cannot access the file because it is being used by another process.
```

### PR DESCRIPTION
**Pull request by martinheidegger**
If the solution doesn't close the database a unclear error is printed. This PR adds the same error display that is used in other parts of the workshopper also when reading the database for a comparsion.

This PR fixes #42.

### CODE REVIEW

File: test/sublevel/invalid_02.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+var level = require('level')
+module.exports = function (databaseDir, callback) {
+  var db = require('level-sublevel')(level(databaseDir))
+  var robots = db.sublevel('robots')
+  var dinosaurs = db.sublevel('dinosaurs')
+
+  ;[robots, dinosaurs].map(function (lev, i) {
+    lev.put('slogan', 1 === i ? 'rawr' : 'beep boop');
```
Comment (syzer) [inline test/sublevel/invalid_02.js]: ;

File: lib/read-db.js [hunk 2]
```diff
@@ -1,19 +1,27 @@
...
+    if (err) {
+      if ( err.type === 'OpenError') {
+        return callback(dir + '\n\n{error.db.not_closed}')
+      } else {
+        return callback(dir + '\n\n{error.mod.unexpected}:\n\n```\n' + ((err && err.stack) || err) + '\n```')
+      }
+    }
+    var result = {}
+    var stream = db.readStream()
+    var error
```
Comment (syzer) [inline lib/read-db.js]: should not declarations do on top of scope?

File: lib/read-db.js [hunk 3]
```diff
@@ -1,19 +1,27 @@
...
-  })
-  stream.on('error', function (err) {
-    error = err
-  })
-  stream.on('end', function () {
-    db.close(function (err) {
-      callback(error || err, result)
+  level(dir, { valueEncoding: valueEncoding }, function (err, db) {
+    if (err) {
+      if ( err.type === 'OpenError') {
```
Comment (syzer) [inline lib/read-db.js]: formatting: extra space ( err.type

File: test/sublevel/invalid_02.js (hunk 1 above)
Comment (martinheidegger) [inline test/sublevel/invalid_02.js]: ; is required since the rest of the file has no ;'s ;)

**Comment by martinheidegger** [comment]
Yep, waiting for #95 to be merged.
